# Generated by Django 4.1.2 on 2022-11-17 12:45

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Картинка')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('post_type', models.TextField(choices=[('материал от подписчиков', 'Subscribers'), ('конкурс', 'Competition'), ('общий пост', 'Base Post'), ('пост с ссылкой', 'Link Post')], default='общий пост')),
            ],
        ),
    ]
