# Generated by Django 4.1.2 on 2022-12-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_images_remove_post_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Это изображение будет расположено на самом верху поста.', null=True, upload_to='posts/', verbose_name='Главное изображение'),
        ),
    ]
