# Generated by Django 4.1.2 on 2022-12-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
