# Generated by Django 4.1.2 on 2022-12-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserfulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='ссылка')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Полезная ссылка',
                'verbose_name_plural': 'Полезные ссылки',
            },
        ),
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='телефонный номер'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.TextField(choices=[('материал от подписчиков', 'Subscribers'), ('конкурс', 'Competition'), ('общий пост', 'Base Post')], default='общий пост', verbose_name='тип публикации'),
        ),
    ]
