# Generated by Django 4.1.2 on 2022-11-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.TextField(choices=[('материал от подписчиков', 'Sub'), ('конкурс', 'Comp')], default='общий пост'),
        ),
    ]
