# Generated by Django 4.1.2 on 2022-12-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_permission_publish_remove_post_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='телефонный номер'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(help_text='Это изображение будет расположено на самом верху поста.', upload_to='posts/', verbose_name='Главное изображение'),
        ),
    ]
