# Generated by Django 4.1.2 on 2022-12-11 12:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_aboutus_alter_contactinformation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='текст'),
        ),
    ]
