# Generated by Django 4.1.2 on 2022-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.TextField(choices=[('материал от подписчиков', 'Subscribers'), ('конкурс', 'Competition'), ('общий пост', 'Base Post')], default='общий пост'),
        ),
    ]
