# Generated by Django 4.1.2 on 2022-11-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_usefullinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsefulLinks',
            new_name='UsefulLink',
        ),
    ]
