# Generated by Django 4.1.2 on 2022-11-21 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendinstance',
            name='country_subject',
            field=models.CharField(default='sadadas', help_text='Укажите ваш район, область, край или республику. Например: Приморский край.', max_length=30, verbose_name='Территориальный субъект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfriendinstance',
            name='locality',
            field=models.CharField(default='asdasd', help_text='Укажите ваш населённый пункт.', max_length=30, verbose_name='Населённый пункт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfriendinstance',
            name='recipient_full_name',
            field=models.CharField(default='asdasdasd', help_text='Укажите ФИО получателя письма, полностью. Например: Иванов Иван Иванович.', max_length=300, verbose_name='ФИО получателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfriendinstance',
            name='zip_code',
            field=models.CharField(default='213121', help_text='Укажите индекс вашего почтового отделения.', max_length=6, verbose_name='Почтовый индекс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfriendinstance',
            name='date_action_use',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 13, 31, 30, 963083, tzinfo=datetime.timezone.utc), verbose_name='дата использования функции "найти друзей"'),
        ),
        migrations.AlterField(
            model_name='userfriendinstance',
            name='postal_address',
            field=models.TextField(help_text='Укажите название улицы, дома, квартиры. Например ул.Красного знамени, д.19, кв.2', verbose_name='Адрес проживания'),
        ),
    ]
