# Generated by Django 4.1.2 on 2022-11-17 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(40)], verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='arctic_region_flag',
            field=models.BooleanField(blank=True, help_text='Нажмите, если вы живёте в одном из регионов арктической зоны России (Список регионов)', null=True, verbose_name='арктический регион'),
        ),
    ]
