# Generated by Django 4.1.2 on 2022-12-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userfriendinstance_date_action_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriendinstance',
            name='country_subject',
            field=models.CharField(help_text='Укажите ваш район, область, край или республику. Например: Приморский край.', max_length=300, verbose_name='Территориальный субъект'),
        ),
        migrations.AlterField(
            model_name='userfriendinstance',
            name='locality',
            field=models.CharField(help_text='Укажите ваш населённый пункт.', max_length=300, verbose_name='Населённый пункт'),
        ),
    ]
