# Generated by Django 4.1.2 on 2022-11-17 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(40)], verbose_name='возраст'),
        ),
    ]
