# Generated by Django 4.1.2 on 2023-01-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userfriendinstance_friendship_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='arctic_region_flag',
            field=models.BooleanField(default=False, verbose_name='арктический регион'),
        ),
    ]
