# Generated by Django 4.1.2 on 2022-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_arctic_region_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='arctic_region_flag',
            field=models.BooleanField(default=False, help_text='Выберете, если вы живёте в одном из регионов арктической зоны России (Список регионов)', verbose_name='арктический регион'),
        ),
    ]
