# Generated by Django 4.1.2 on 2022-11-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_arctic_region_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='arctic_region_flag',
            field=models.BooleanField(default=False, verbose_name='арктический регион'),
        ),
    ]
