# Generated by Django 4.1.2 on 2022-11-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_arctic_region_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='arctic_region_flag',
            field=models.TextField(choices=[('True', 'Arctic'), ('False', 'Not Arctic')], default='False', verbose_name='арктический регион'),
        ),
    ]
