# Generated by Django 4.1.2 on 2022-11-18 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_arctic_region_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 10, 41, 38, 180506), verbose_name='дата рождения'),
            preserve_default=False,
        ),
    ]
