# Generated by Django 4.1.2 on 2022-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_user_age_user_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(default=2022, verbose_name='дата рождения'),
            preserve_default=False,
        ),
    ]
