# Generated by Django 4.1.2 on 2022-11-18 14:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_user_birthdate_user_birth_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriendInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network_nickname', models.CharField(max_length=60)),
                ('postal_address', models.TextField()),
                ('date_action_use', models.DateTimeField(default=datetime.datetime(2022, 11, 18, 14, 48, 31, 109771))),
                ('user_friends', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
