# Generated by Django 4.1.2 on 2022-11-18 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_userfriendinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriendinstance',
            name='date_action_use',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 14, 50, 19, 908254, tzinfo=datetime.timezone.utc)),
        ),
    ]
