# Generated by Django 4.1.2 on 2022-11-18 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_userfriendinstance_date_action_use'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfriendinstance',
            options={'verbose_name': 'Пользователь в базе данных друзей', 'verbose_name_plural': 'Пользователи в базе данных друзей'},
        ),
        migrations.AlterField(
            model_name='userfriendinstance',
            name='date_action_use',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 16, 47, 24, 261595, tzinfo=datetime.timezone.utc)),
        ),
    ]
