# Generated by Django 4.1.2 on 2022-11-18 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_userfriendinstance_date_action_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriendinstance',
            name='date_action_use',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 17, 22, 37, 523181, tzinfo=datetime.timezone.utc), verbose_name='дата использования функции "найти друзей"'),
        ),
        migrations.AlterField(
            model_name='userfriendinstance',
            name='postal_address',
            field=models.TextField(verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='userfriendinstance',
            name='social_network_nickname',
            field=models.CharField(help_text='Не забудьте указать название социальной сети', max_length=60, verbose_name='Никнейм в социальной сети'),
        ),
        migrations.AlterField(
            model_name='userfriendinstance',
            name='user_friends',
            field=models.TextField(blank=True, null=True, verbose_name='список друзей пользователя'),
        ),
    ]
