# Generated by Django 4.1.2 on 2022-11-18 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_userfriendinstance_date_action_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriendinstance',
            name='date_action_use',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 17, 22, 55, 985589, tzinfo=datetime.timezone.utc), verbose_name='дата использования функции "найти друзей"'),
        ),
        migrations.AlterField(
            model_name='userfriendinstance',
            name='social_network_nickname',
            field=models.CharField(help_text='Не забудьте указать название социальной сети', max_length=60, verbose_name='Имя в социальной сети'),
        ),
    ]
